### ISSUE TITLE
Ability to override validators & `required` message

### ISSUE THREAD

**Issue by billpull** [ololabs/principled-forms#13]
When using a required field it would be useful to allow changing the message displayed to the user.

For a case where I had to override an email validation message I created a new `Field.required` with a `type: Type.email` and a custom validator.

ex: `my-project/lib/email.ts`
```ts
import { regex } from '@olo/principled-forms/validators';

const EMAIL_RE = /.+@.+\..+/;
const invalidEmailMessage = 'Email should contain "@" and "."';
export const validator = regex(EMAIL_RE, () => invalidEmailMessage);
```

some usage
```ts
import { validator as emailValidator } from 'my-project/lib/email';

Field.required({ value: '', type: Type.email, validators: [emailValidator] });
```

Loses some convenience factor but overall I can extend my way to any custom field validation I want in a similar manner.

Required fields seem to be trickier since the validation is not part of the [ `validators` array](https://github.com/ololabs/principled-forms/blob/d6147508706e7c16dd241658b1e3a39c8584f1da/packages/principled-forms/src/validity.ts#L73). Looking at the current implementation I believe to override this message would need to construct a new implementation of `MinimalField` that calls a custom[ `_validate`](https://github.com/ololabs/principled-forms/blob/b5872103e1c3cc1efc40a6d29973f081a11d0da8/packages/principled-forms/src/field/index.ts#L20) with custom `Validity.required`.

Could be overlooking something.

**Comment by chriskrycho** [comment]
Yeah, I need to land #11 because I plan to include that functionality there – I noted the same thing.

**Comment by chriskrycho** [comment]
I think we can trivially extend `RequiredField` to allow the same degree of customization – it would just be a custom property on the options hash, so you'd do this:

```ts
Field.required({
  value: '',
  type: Type.email,
  validators: [emailValidator],
  errorMessage: 'Alas: the field has proven to be absent.'
});
```

**Comment by chriskrycho** [comment]
The now-complete #11 address both of those, @bill. Really helpful feedback; thank you! This will get closed as soon as we merge that.
