### ISSUE TITLE
Cannot import into an Ember app

### ISSUE THREAD

**Issue by tansongyang** [ololabs/principled-forms#6]
I tried to import `Field`, and there were no type errors:

```TypeScript
import { Field } from '@olo/principled-forms';
```

However, when I actually try to do anything with it, e.g. `console.log(Field.optional)`, I get the following error:

> Error: Could not find module `@olo/principled-forms` imported from `principled-forms-repro/components/issue-repro`

[Repro repository](https://github.com/tansongyang/principled-forms-repro/tree/cannot-import)

I noticed the following message in Ember CLI and am wondering if it could be related:

> The package `@olo/principled-forms` is not a properly formatted package, we have used a fallback lookup to resolve it at `C:\GitHub\principled-forms-repro\node_modules\@olo\principled-forms`. This is generally caused by an addon not having a `main` entry point (or `index.js`).

**Comment by chriskrycho** [comment]
🤔I'll pull it and see if I can figure out what the problem is shortly. That error message almost certainly *is* the problem.
