### ISSUE TITLE
Should `<label>`, `<input />`, and `error` be decoupled?

### ISSUE THREAD

**Issue by billpull** [ololabs/principled-forms#9]
When experimenting with creating an input with a button/icon I used the `form-field` component in block form but my inner template ended up looking like

```hbs
{{#form-field as |form|}}
  <label for={{form.id}} class={{labelClass}}>
    {{label}}
  </label>

  <input
      type={{form.model.type}}
      oninput={{action 'handleInput' value='target.value'}}
      onchange={{action 'handleChange' value='target.value'}}
      class={{inputClass}}
      value={{form.model.value}}
  />

  <!--
     My custom code
   -->

  {{#if form.isInvalid}}
    <span class={{errorClass}}>{{form.model.validity.reason}}</span>
  {{/if}}
{{/form-field}}
```

Thinking these should be separate components so any sort of validity related functionality isn't lost when extending this component. Probably at minimum creating a `form-field-input` component would help since most of the utility is from the input itself.

**Comment by chriskrycho** [comment]
Interesting. Let's pair on this tomorrow, as I *think* this is roughly what @tansongyang and I intended if people wanted to override it, but you're right that it adds a lot of lift depending on how much you want to customize it.

**Comment by billpull** [comment]
Per discussion the consumer of this package should extend in order to change DOM structure.

**Comment by tansongyang** [comment]
@billpull or @chriskrycho, I was out all weekend, so, if you have the time, could you share the reasons why we stayed with this so that we can have it documented?
